# Generated by Django 3.2 on 2023-01-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documenmt/')),
                ('author', models.CharField(blank=True, max_length=90, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('word_count', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_file', models.IntegerField(default=5)),
                ('similarity_score', models.IntegerField(default=70)),
            ],
            options={
                'verbose_name': 'App Configuration',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=100)),
                ('year_details', models.JSONField(blank=True, null=True)),
                ('progress', models.FloatField(blank=True, default=0)),
                ('complete', models.BooleanField(blank=True, default=False)),
                ('threshold_similarity', models.IntegerField(blank=True, default=0)),
                ('threshold_file', models.IntegerField(blank=True, default=0)),
                ('status', models.CharField(blank=True, choices=[('Complete', 'Complete'), ('Failed', 'Failed'), ('Inprogress', 'Inprogress')], max_length=100, null=True)),
                ('error', models.CharField(blank=True, choices=[('file_not_found', 'File not found'), ('no_file_with_unique_content', 'No file with unique content'), ('unknown_file_extension', 'Unknown file extension'), ('unknown_author', 'Unknown author'), ('threshold_not_found', 'Threshold not found')], max_length=100, null=True)),
                ('completed_file', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('files', models.ManyToManyField(blank=True, to='documentchecker.File')),
                ('selected_files', models.ManyToManyField(blank=True, related_name='selected_files', to='documentchecker.File')),
            ],
        ),
    ]
