# Generated by Django 3.2 on 2023-01-10 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentchecker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threshold',
            name='similarity_score',
            field=models.IntegerField(default=70, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
