# Generated by Django 3.2 on 2023-01-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentchecker', '0002_alter_threshold_similarity_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='error',
            field=models.CharField(blank=True, choices=[('1', 'File not found'), ('2', 'No file with unique content'), ('3', 'Unknown author'), ('4', 'Threshold not found'), ('5', 'Error in file')], max_length=100, null=True),
        ),
    ]
